"""Chapter 06 — Push Notifications: FoodDash Push Subscriber

This script simulates the browser-side push subscription flow:

    1. Generate VAPID key pair (simulating what the browser does internally)
    2. Create a push subscription object (endpoint + keys)
    3. Send the subscription to the FoodDash server
    4. Place an order to trigger a push notification
    5. Advance the order through statuses, showing how each push is configured

The key insight: after subscribing, the client does NOT maintain a connection.
It registers once, then walks away. The server can reach it later through the
push service — even if the app is closed, the browser is closed, or the
device is asleep.

Run with:
    uv run python -m chapters.ch06_push_notifications.subscriber

Requires the server to be running:
    uv run uvicorn chapters.ch06_push_notifications.server:app --port 8006
"""

from __future__ import annotations

import asyncio
import base64
import json
import os
import sys
import time

import httpx

BASE_URL = "http://localhost:8006"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def print_header(title: str) -> None:
    width = 70
    print()
    print("=" * width)
    print(f"  {title}")
    print("=" * width)


def print_step(number: int, title: str) -> None:
    print(f"\n  --- Step {number}: {title} ---\n")


def print_detail(label: str, value: str, indent: int = 4) -> None:
    prefix = " " * indent
    print(f"{prefix}{label}: {value}")


def print_json(data: dict, indent: int = 4) -> None:
    prefix = " " * indent
    formatted = json.dumps(data, indent=2)
    for line in formatted.split("\n"):
        print(f"{prefix}{line}")


def urlsafe_b64encode_no_pad(data: bytes) -> str:
    """Base64url encode without padding (as used in Web Push keys)."""
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


# ---------------------------------------------------------------------------
# Subscription simulation
# ---------------------------------------------------------------------------

def generate_mock_subscription() -> tuple[dict, dict]:
    """Simulate what the browser does during PushManager.subscribe().

    In a real browser:
    1. Browser generates an ECDH key pair (P-256 curve)
    2. Browser contacts the push service to create a subscription
    3. Push service returns a unique endpoint URL
    4. Browser bundles: endpoint + public key + auth secret

    We simulate this with random bytes since we can't contact a real
    push service from a CLI script. The educational value is in
    understanding the structure, not the actual crypto.
    """
    # Simulate ECDH P-256 public key (65 bytes: 0x04 prefix + 32-byte X + 32-byte Y)
    # In reality, this is generated by the browser's crypto API
    p256dh_bytes = b"\x04" + os.urandom(64)  # Uncompressed P-256 point
    p256dh = urlsafe_b64encode_no_pad(p256dh_bytes)

    # Simulate auth secret (16 random bytes)
    # Shared between browser and server for HKDF key derivation
    auth_bytes = os.urandom(16)
    auth = urlsafe_b64encode_no_pad(auth_bytes)

    # Simulate push service endpoint
    # In reality, this is a URL on fcm.googleapis.com, updates.push.services.mozilla.com, etc.
    subscription_id = urlsafe_b64encode_no_pad(os.urandom(32))
    endpoint = f"https://push.example.com/v1/subscriptions/{subscription_id}"

    subscription = {
        "endpoint": endpoint,
        "keys": {
            "p256dh": p256dh,
            "auth": auth,
        },
    }

    # Also return the "internal" state (what the browser keeps private)
    internal_state = {
        "p256dh_public": p256dh,
        "p256dh_bytes_length": len(p256dh_bytes),
        "auth_bytes_length": len(auth_bytes),
        "note": (
            "The browser keeps the PRIVATE key of the ECDH pair. "
            "Only the public key (p256dh) is shared. The push service "
            "and our server never see the private key."
        ),
    }

    return subscription, internal_state


# ---------------------------------------------------------------------------
# Main flow
# ---------------------------------------------------------------------------

async def main() -> None:
    print_header("Chapter 06: Push Notification Subscriber")
    print()
    print("  FoodDash push notification demo.")
    print("  This simulates the browser-side subscription flow and")
    print("  demonstrates how push notifications reach users who have")
    print("  NO active connection to the server.")
    print()
    print("  Key difference from Ch01-Ch05:")
    print("    - Ch01 (Request-Response): Client must send a request")
    print("    - Ch02 (Short Polling):    Client must keep asking")
    print("    - Ch03 (Long Polling):     Client must hold a connection")
    print("    - Ch04 (SSE):              Client must keep a stream open")
    print("    - Ch05 (WebSocket):        Client must keep a TCP connection")
    print("    - Ch06 (Push):             Client subscribes ONCE, then disconnects")
    print()

    # Check server availability
    try:
        async with httpx.AsyncClient(base_url=BASE_URL, timeout=5.0) as client:
            resp = await client.get("/health")
            health = resp.json()
    except httpx.ConnectError:
        print(f"  ERROR: Cannot connect to server at {BASE_URL}")
        print("  Start the server first:")
        print("    uv run uvicorn chapters.ch06_push_notifications.server:app --port 8006")
        print()
        return

    print(f"  Server status: {health['status']}")
    print(f"  Push mode: {health['capabilities']['mode']}")
    print(f"  pywebpush available: {health['capabilities']['webpush_library']}")
    print()

    # -----------------------------------------------------------------------
    # Step 1: Get the server's VAPID public key
    # -----------------------------------------------------------------------

    print_step(1, "Get Server's VAPID Public Key")

    print("  In a real browser, your JavaScript would do:")
    print()
    print("    const response = await fetch('/vapid-public-key');")
    print("    const { public_key } = await response.json();")
    print()
    print("  The VAPID public key identifies YOUR server to the push service.")
    print("  When we subscribe, the push service records which server is")
    print("  allowed to send pushes to this subscription.")
    print()

    async with httpx.AsyncClient(base_url=BASE_URL, timeout=10.0) as client:
        resp = await client.get("/vapid-public-key")
        vapid_data = resp.json()

    print_detail("VAPID public key", vapid_data["public_key"][:40] + "...")
    print_detail("Key length", f"{len(vapid_data['public_key'])} chars (base64url-encoded P-256 point)")
    print()
    print("  This key will be passed to PushManager.subscribe() so the push")
    print("  service knows to only accept pushes from our server.")

    # -----------------------------------------------------------------------
    # Step 2: Generate a push subscription (simulating the browser)
    # -----------------------------------------------------------------------

    print_step(2, "Generate Push Subscription")

    print("  In a real browser, this is what happens when you call:")
    print()
    print("    const subscription = await registration.pushManager.subscribe({")
    print("      userVisibleOnly: true,")
    print("      applicationServerKey: urlBase64ToUint8Array(vapidPublicKey)")
    print("    });")
    print()
    print("  The browser:")
    print("    1. Generates an ECDH key pair (P-256 curve)")
    print("    2. Contacts the push service (FCM, Mozilla, etc.)")
    print("    3. Creates a unique subscription with an endpoint URL")
    print("    4. Returns a PushSubscription object with:")
    print("       - endpoint: where to POST encrypted messages")
    print("       - keys.p256dh: browser's ECDH public key")
    print("       - keys.auth: shared authentication secret")
    print()

    subscription, internal_state = generate_mock_subscription()

    print("  Generated subscription:")
    print_json(subscription)
    print()
    print("  Internal browser state (NOT shared with server):")
    print_json(internal_state)
    print()
    print("  The subscription object is ~200 bytes. Compare to a WebSocket")
    print("  connection which requires ~30KB of persistent state (TCP buffers,")
    print("  TLS session, application state). Push is 150x lighter on the server.")

    # -----------------------------------------------------------------------
    # Step 3: Send subscription to the server
    # -----------------------------------------------------------------------

    print_step(3, "Register Subscription with Server")

    print("  Now we send the subscription to our server. This is the ONLY")
    print("  time the client needs to talk to us. After this, the client")
    print("  can close the app, turn off the screen, even restart the phone.")
    print("  The server can still reach them through the push service.")
    print()

    customer_id = f"cust_{os.urandom(4).hex()}"

    async with httpx.AsyncClient(base_url=BASE_URL, timeout=10.0) as client:
        resp = await client.post("/subscribe", json={
            "customer_id": customer_id,
            "endpoint": subscription["endpoint"],
            "keys": subscription["keys"],
        })
        sub_result = resp.json()

    print("  Server response:")
    print_json(sub_result)
    print()
    print("  The server stored our subscription. It now has everything it needs")
    print("  to send us encrypted push notifications at any point in the future.")

    # -----------------------------------------------------------------------
    # Step 4: Place an order (triggers push)
    # -----------------------------------------------------------------------

    print_step(4, "Place an Order (Triggers Push Notification)")

    print("  Now let's place an order. The server will immediately send a")
    print("  push notification to confirm it — even though we have NO active")
    print("  connection to the server. The push travels through the push service.")
    print()

    async with httpx.AsyncClient(base_url=BASE_URL, timeout=10.0) as client:
        resp = await client.post("/orders", json={
            "customer_name": "Alice",
            "restaurant_id": "rest_01",
            "item_ids": ["item_01", "item_02", "item_03"],
        })
        order_result = resp.json()

    order_id = order_result["order_id"]
    print(f"  Order placed: {order_id}")
    print(f"  Status: {order_result['status']}")
    print(f"  Push sent: {order_result['push_sent']}")
    print()

    if order_result.get("push_details"):
        details = order_result["push_details"]
        print("  Push notification details:")
        print(f"    Title: {details['notification']['title']}")
        print(f"    Body: {details['notification']['body']}")
        print(f"    Urgency: {details['notification']['urgency']}")
        print(f"    TTL: {details['notification']['ttl']}s")
        print(f"    Topic: {details['notification']['topic']}")
        print()

        if details.get("results"):
            result = details["results"][0]
            if result.get("status") == "no_subscription":
                print(f"    Note: {result.get('explanation', 'No subscription found')}")
                print()
                print("    This is expected: the order was placed with a new customer ID")
                print("    that doesn't match our subscription's customer ID. In a real")
                print("    app, the customer ID would match.")
            elif result.get("encryption_steps"):
                print("  Encryption steps (what the server would do):")
                for step in result["encryption_steps"]:
                    print(f"    {step}")
            elif result.get("encryption"):
                print("  Encryption used:")
                print_json(result["encryption"], indent=6)

    # -----------------------------------------------------------------------
    # Step 5: Advance order through statuses
    # -----------------------------------------------------------------------

    print_step(5, "Advance Order Through Statuses")

    print("  Each status transition sends a push notification with different")
    print("  urgency, TTL, and the same Topic (to replace, not stack).")
    print()
    print("  Topic: 'order-status-{order_id}' means each new notification")
    print("  REPLACES the previous one. The user sees ONE notification with")
    print("  the latest status, not seven stacked notifications.")
    print()

    statuses_to_advance = [
        "confirmed",
        "preparing",
        "ready",
        "picked_up",
        "en_route",
        "delivered",
    ]

    async with httpx.AsyncClient(base_url=BASE_URL, timeout=10.0) as client:
        for expected_status in statuses_to_advance:
            resp = await client.post(f"/orders/{order_id}/advance")
            if resp.status_code != 200:
                print(f"  Error advancing order: {resp.text}")
                break

            advance_result = resp.json()
            notification = advance_result.get("notification", {})

            print(f"  {advance_result['previous_status']} -> {advance_result['new_status']}")
            if notification:
                print(f"    Push: \"{notification['title']}\" — {notification['body']}")
                print(f"    Urgency: {notification['urgency']}, TTL: {notification['ttl']}s, Topic: {notification['topic']}")
            print()

    # -----------------------------------------------------------------------
    # Step 6: Inspect push log
    # -----------------------------------------------------------------------

    print_step(6, "Inspect Push Log")

    print("  The server keeps a log of all push attempts. Let's see what")
    print("  was sent (or would have been sent).")
    print()

    async with httpx.AsyncClient(base_url=BASE_URL, timeout=10.0) as client:
        resp = await client.get("/push-log")
        log = resp.json()

    print(f"  Total pushes attempted: {log['total_pushes']}")
    print(f"  pywebpush available: {log['webpush_available']}")
    print(f"  VAPID configured: {log['vapid_configured']}")
    print()

    if log["pushes"]:
        latest = log["pushes"][0]
        print("  Latest push attempt:")
        print_detail("Status", latest.get("status", "unknown"))
        print_detail("Method", latest.get("method", "unknown"))
        print_detail("Payload size", f"{latest.get('payload_size_bytes', 0)} bytes")
        print_detail("Urgency", latest.get("urgency", "normal"))
        print_detail("TTL", f"{latest.get('ttl', 0)}s")
        if latest.get("topic"):
            print_detail("Topic", latest["topic"])

    # -----------------------------------------------------------------------
    # Step 7: Check subscriptions
    # -----------------------------------------------------------------------

    print_step(7, "Check Server-Side Subscription State")

    async with httpx.AsyncClient(base_url=BASE_URL, timeout=10.0) as client:
        resp = await client.get("/subscriptions")
        subs = resp.json()

    print(f"  Total customers: {subs['total_customers']}")
    print(f"  Total subscriptions: {subs['total_subscriptions']}")
    print(f"  Total storage: {subs['total_storage_bytes']} bytes")
    print()
    print("  Memory comparison:")
    print_detail("Push subscription", subs['comparison']['push_per_user'])
    print_detail("WebSocket connection", subs['comparison']['websocket_per_user'])
    print_detail("Ratio", subs['comparison']['ratio'])

    # -----------------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------------

    print_header("Summary — What We Demonstrated")
    print()
    print("  1. SUBSCRIPTION: Client subscribes ONCE, then can disconnect.")
    print("     No persistent connection needed. Server stores ~200 bytes.")
    print()
    print("  2. PUSH DELIVERY: Server sends through the push service.")
    print("     The push service maintains device connections, not us.")
    print("     Works even when: app closed, browser closed, device asleep.")
    print()
    print("  3. ENCRYPTION: Payloads encrypted end-to-end (ECDH + AES-128-GCM).")
    print("     The push service (Google/Mozilla) cannot read notification content.")
    print()
    print("  4. DELIVERY CONTROL:")
    print("     - Urgency: very-low/low/normal/high (affects battery optimization)")
    print("     - TTL: how long push service holds undelivered messages")
    print("     - Topic: replace stale notifications instead of stacking")
    print()
    print("  5. TRADE-OFF: We traded direct control for reach.")
    print("     - WebSocket: instant delivery, but only while connected")
    print("     - Push: eventual delivery, but works when disconnected")
    print("     - FoodDash uses BOTH: WebSocket for chat, Push for alerts")
    print()
    print("  Next: Chapter 07 — Pub/Sub (decoupling server-side reactions)")
    print()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\n  Goodbye!")
